NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

register_user:
    type: rest
    resource: AppBundle\Controller\RegisterController
    methods: POST
    
confirm_user:
    path: /register/confirm/{token}
    defaults: { _controller: AppBundle:Register:confirm }
    methods: GET

mailer:
    type: rest
    resource: AppBundle\Controller\MailerController
    methods: POST
    prefix: mailer

users:
    type: rest
    resource: AppBundle\Controller\UserController

images:
    type: rest
    resource: AppBundle\Controller\ImageController

galleries:
    type: rest
    resource: AppBundle\Controller\GalleryController

items:
    type: rest
    resource: AppBundle\Controller\ItemController

pages:
    type: rest
    resource: AppBundle\Controller\PageController

blogs:
    type: rest
    resource: AppBundle\Controller\BlogController

options:
    type: rest
    resource: AppBundle\Controller\OptionController

components:
    type: rest
    resource: AppBundle\Controller\ComponentController

products:
    type: rest
    resource: AppBundle\Controller\ProductController

locale:
    type: rest
    resource: AppBundle\Controller\LocaleController

localization:
    type: rest
    resource: AppBundle\Controller\LocalizationController
