NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

register_user:
    type: rest
    resource: AppBundle\Controller\RegisterController
    methods: POST
    
confirm_user:
    path: /register/confirm/{token}
    defaults: { _controller: AppBundle:Register:confirm }
    methods: GET

users:
    type: rest
    resource: AppBundle\Controller\UserController

images:
    type: rest
    resource: AppBundle\Controller\ImageController

items:
    type: rest
    resource: AppBundle\Controller\ItemController

pages:
    type: rest
    resource: AppBundle\Controller\PageController

options:
    type: rest
    resource: AppBundle\Controller\OptionController

components:
    type: rest
    resource: AppBundle\Controller\ComponentController
