_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    
app:
    type: annotation
    resource: 'AppBundle\Controller\DefaultController'

mailer:
    type: rest
    resource: AppBundle\Controller\MailerController
    methods: POST
    prefix: mailer
    
assets:
    type: rest
    resource: AppBundle\Controller\AssetController

users:
    type: rest
    resource: AppBundle\Controller\UserController

images:
    type: rest
    resource: AppBundle\Controller\ImageController

galleries:
    type: rest
    resource: AppBundle\Controller\GalleryController

items:
    type: rest
    resource: AppBundle\Controller\ItemController

pages:
    type: rest
    resource: AppBundle\Controller\PageController
    
metadatas:
    type: rest
    resource: AppBundle\Controller\MetadataController

blogs:
    type: rest
    resource: AppBundle\Controller\BlogController

options:
    type: rest
    resource: AppBundle\Controller\OptionController

components:
    type: rest
    resource: AppBundle\Controller\ComponentController

languages:
    type: rest
    resource: AppBundle\Controller\LanguageController

locale:
    type: rest
    resource: AppBundle\Controller\LocaleController

travel:
    type: rest
    resource: AppBundle\Controller\TravelController
