security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        mailer:
            pattern: ^/mailer
            methods: ['POST']
            security: false
            anonymous: true
           
        users:
            pattern: ^/users
            fos_oauth: true
            stateless: true
            anonymous: false

        api_user:
            pattern: ^/user
            fos_oauth: true
            stateless: true
            anonymous: false
            
        api_edit:
            pattern: ^/
            methods: ['POST', 'PUT', 'DELETE', 'OPTIONS']
            fos_oauth: true
            stateless: true
            anonymous: false
            
        api_read:
            pattern: ^/
            methods: ['GET']
            security: false
            anonymous: true
            
    access_control:
        - {path: ^/users, roles: ROLE_ADMIN}
        - {methods: ['DELETE'], roles: ROLE_ADMIN}
